### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by punyashah** [DataCurationNetwork/CURATED#5]
Need detailed about us page

**Comment by bdezray** [comment]
Here is the information for the About Us page!

What is the Data Curation Network? 

The Data Curation Network is a community-led network of professional data curators that aim to empower researchers to publish high quality data in an ethical and FAIR way, collaborate to advance the art and science of data curation by creating, adopting, and openly sharing best practices, and support thoughtful, innovative, and inclusive data curation training and professional development opportunities. 

What is data curation? 

Data curation enables data discovery and retrieval, maintains data quality, adds value, and provides for re-use over time through activities including authentication, archiving, metadata creation, digital preservation, and transformation. Data curators collaborate with researchers to share data ethically and in ways that are findable, accessible, interoperable, and reusable (FAIR). 

What is the CURATED Training?

The Data Curation Network is pleased to provide online CURATED training. The goal of the CURATED Training is to offer an introduction to applied data curation. This training is designed for those completely new to data curation, those hoping to refresh their data curation skills, or those looking to apply data curation knowledge to the management of their own research data. 

Learners will:
•	Increase understanding of data curation practices and tools.
•	Apply the CURATE(D) model to a data deposit.

The CURATED training modules were developed as part of the Specialized Data Curation Training program funded by the Institute of Museum and Library Services (IMLS) ##RE-85-18-004018.

CURATED Training Citation:
[Blake, Mara](https://orcid.org/0000-0003-2888-8024); [Borda, Susan](https://orcid.org/0000-0002-9424-6962); [Carlson, Jake](https://orcid.org/0000-0003-2733-0969); [Darragh, Jennifer](https://orcid.org/0000-0002-8843-5089); [Fearon, David](https://orcid.org/0000-0002-4292-9171); Hadley, Hannah; [Herndon, Joel](https://orcid.org/0000-0001-9995-9040); [Johnston, Lisa](https://orcid.org/0000-0001-6908-9240); [Kalt, Marley](https://orcid.org/0000-0002-1354-1020); [Kozlowski, Wendy](https://orcid.org/0000-0001-6539-3798); [Hess, Sophia Lafferty](https://orcid.org/0000-0001-9995-9040); [Moore, Jennifer](https://orcid.org/0000-0001-6628-6820); [Narlock, Mikala](https://orcid.org/0000-0002-2730-7542); [Scott, Dorris](https://orcid.org/0000-0002-3884-7069); [Vitale, Cynthia Hudson](https://orcid.org/0000-0001-5581-5678); [Wham, Briana Ezray](https://orcid.org/0000-0002-9240-8606); [Wright, Sarah](http://orcid.org/0000-0002-1502-131X) (2022), Data Curation Network: CURATED Training. https://datacurationnetwork.github.io/CURATED/
